language: node_js
node_js: stable
branches:
  only:
  - master
 cache:
   directories:
     - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_f32e69b43e03_key -iv $encrypted_f32e69b43e03_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'liubiaomr'
- git config --global user.email liubiaomr@163.com

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy
